### ISSUE TITLE
Conflicting parameters using parchment in 1.16 forge

### ISSUE THREAD

**Issue by noeppi-noeppi** [ParchmentMC/Parchment#70] opened 2021-09-26 11:02 UTC
**Minecraft version:** 1.16.5
**Mappings version:** 2021.08.29
**Librarian version:** 1.1.4

In `ITextProperties` (`FormattedText` with mojmap) the method `of(String, Style)` contains an anonymous class where the parameter `pStyle` from the method in `ITextProperties` conflicts with a parameter from a method inside the anonymous class. This causes all style information including click and hover events to be missing from the chat ingame. This is becasue instead of the style from the formatted text being merged onto the base style, the base style is merged onto itself.

**Comment by sciwhiz12** [comment] 2021-10-06 03:08
Fixed by ade265e2d8d06c4f66dc12e02590ac422fc63fe3. We'll look into fixing the root cause of this at a later point after more investigation, but for now this particular issue is fixed by removing the mapping.

**Closed as completed by sciwhiz12** 2021-10-06 03:08 UTC
Labels: bug, 1.16.x
